### ISSUE TITLE
Encountering a problem when running `rasa train`

### ISSUE THREAD

**Issue by Akshay2996** [RasaHQ/rasa-masterclass#2]
NameError: Cannot access action 'search_provider', as that name is not a registered action for this domain. Available actions are:
         - action_listen
         - action_restart
         - action_session_start
         - action_default_fallback
         - action_deactivate_form
         - action_revert_fallback_events
         - action_default_ask_affirmation
         - action_default_ask_rephrase
         - action_back
         - action_facility_search
         - utter_ask_location
         - utter_cheer_up
         - utter_did_that_help
         - utter_goodbye
         - utter_greet
         - utter_happy
         - utter_how_can_i_help

Please help I am not able to figure out the problem

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @alwx will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by Akshay2996** [comment]
This issue comes when I write intent separately in my domain.yml file and doesn't include it in my actions.
