### ISSUE TITLE
Predefined Responses

### ISSUE THREAD

**Issue by swetabhmukherjee** [RasaHQ/rasa-masterclass#4]
Hi all. I want to create some predefined responses for the users. I want the user to pick from one of the 3 defined responses the bot to act accordingly. How can I achieve this?

**Comment by sara-tagger** [comment]
Thanks for the issue, @erohmensing will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
Hi @swetabhmukherjee , [buttons](https://rasa.com/docs/rasa/core/domains/#images-and-buttons) are a great way to do that!

**Comment by swetabhmukherjee** [comment]
Thanks. I think I should close this now :)
