### ISSUE TITLE
Ansible playbook fails to provision the instance

### ISSUE THREAD

**Issue by sinistersig** [RasaHQ/rasa-masterclass#5]
I have been following along with the masterclass pdf, however im stuck installing rasa x on GCP. While runnning the script I got the following error.

```
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["/usr/local/sbin/pip", "uninstall",
 "-y", "docker-py"], "msg": "\n:stderr: *****************************************************
***************************\nPython 2 is deprecated. Upgrade to pip3 as soon as possible.\nSe
e https://cloud.google.com/python/docs/python2-sunset\n\nTo suppress this warning, create an 
empty ~/.cloudshell/no-pip-warning file.\nThe command will automatically proceed in 5 seconds
 or on any key.\n****************************************************************************
****\n/usr/local/sbin/pip: line 19: /usr/bin/pip: No such file or directory\n"}
```

Any help would be appreciated.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @Ghostvv will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by Ghostvv** [comment]
from the message above, I think you need to install python3

**Comment by sinistersig** [comment]
Python3 was installed ok but I believe the issues are with the playbook not using `pip3` instead `pip`

**Comment by Ghostvv** [comment]
which masterclass is not working?

**Comment by sinistersig** [comment]
Chapter 9, following the ebook that is currently available on the Rasa site

**Comment by karen-white** [comment]
hey @sinistersig, which version of Rasa X are you installing?

**Comment by sinistersig** [comment]
Just tried with 0.31.5 and it worked, the version in the book is 0.23.3
