### ISSUE TITLE
Synoymns fomat depricated 

### ISSUE THREAD

**Issue by sdoshi579** [RasaHQ/rasa-masterclass#6]
(facility_type:xyz-abc) is depricated and new format for synonyms is {"entity":"facility_type", "value": "xyz-abc"}

**Comment by sara-tagger** [comment]
Thanks for the issue, @tabergma will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by JustinaPetr** [comment]
Thank you @sdoshi579 . We developed the Rasa Masterclass content with the version 1.8.0 so it would be best to use it when following the series. Hopefully we can update the content to the latest Rasa release too. I have updated the readme locking the Rasa version there. Thank you for pointing this out! :)
